### ISSUE TITLE
Not able to deploy UI5-TS application into cloufoundry

### ISSUE THREAD

**Issue by chandeep2013** [SAP-samples/ui5-typescript-control-library#14]
Hello,

"npm run build" after running this command **dist** folder is creating. But how can I deploy app into cf.
It is not generating **mta_archives** file.

Thanks..!

**Comment by akudev** [comment]
I'm sorry, but this is outside the scope of this project. It focuses on how a UI5 library is implemented in TypeScript, as opposed to implementing it in JavaScript. Deployment to a specific kind of platform does not depend on whether the library is implemented in TypeScript or not (the build result is JavaScript in both cases).
